"""
Property-based tests for DecisionEngine.

These tests validate the correctness properties related to confidence score
bounds, low confidence flagging, and decision aggregation.
"""

import pytest
from hypothesis import given, strategies as st, assume, settings, HealthCheck
import numpy as np

from umpirai.decision.decision_engine import DecisionEngine, DecisionEngineConfig
from umpirai.models.data_models import (
    Detection,
    DetectionResult,
    Frame,
    TrackState,
    Trajectory,
    Position3D,
    Vector3D,
    BoundingBox,
    EventType,
)
from umpirai.calibration.calibration_manager import CalibrationData, Point2D


# ============================================================================
# Hypothesis Strategies
# ============================================================================

@st.composite
def position_3d_strategy(draw):
    """Generate random 3D positions."""
    return Position3D(
        x=draw(st.floats(min_value=-10.0, max_value=10.0)),
        y=draw(st.floats(min_value=0.0, max_value=5.0)),
        z=draw(st.floats(min_value=-20.0, max_value=20.0))
    )


@st.composite
def vector_3d_strategy(draw):
    """Generate random 3D vectors."""
    return Vector3D(
        vx=draw(st.floats(min_value=-30.0, max_value=30.0)),
        vy=draw(st.floats(min_value=-30.0, max_value=30.0)),
        vz=draw(st.floats(min_value=-30.0, max_value=30.0))
    )


@st.composite
def detection_strategy(draw, class_id=None, confidence=None):
    """Generate random Detection objects."""
    if class_id is None:
        class_id = draw(st.integers(min_value=0, max_value=7))
    if confidence is None:
        confidence = draw(st.floats(min_value=0.0, max_value=1.0))
    
    return Detection(
        class_id=class_id,
        class_name=f"class_{class_id}",
        bounding_box=BoundingBox(
            x=draw(st.floats(min_value=0.0, max_value=1280.0)),
            y=draw(st.floats(min_value=0.0, max_value=720.0)),
            width=draw(st.floats(min_value=10.0, max_value=200.0)),
            height=draw(st.floats(min_value=10.0, max_value=200.0))
        ),
        confidence=confidence,
        position_3d=draw(st.one_of(st.none(), position_3d_strategy()))
    )


@st.composite
def trajectory_strategy(draw, min_length=1, max_length=30):
    """Generate random Trajectory objects."""
    length = draw(st.integers(min_value=min_length, max_value=max_length))
    
    positions = [draw(position_3d_strategy()) for _ in range(length)]
    timestamps = sorted([draw(st.floats(min_value=0.0, max_value=10.0)) for _ in range(length)])
    velocities = [draw(vector_3d_strategy()) for _ in range(length)]
    
    return Trajectory(
        positions=positions,
        timestamps=timestamps,
        velocities=velocities,
        start_position=positions[0] if positions else Position3D(x=0.0, y=1.0, z=-10.0),
        end_position=positions[-1] if positions else None,
        speed_max=draw(st.floats(min_value=0.0, max_value=50.0)),
        speed_avg=draw(st.floats(min_value=0.0, max_value=40.0))
    )


@st.composite
def calibration_strategy(draw):
    """Generate random CalibrationData objects."""
    return CalibrationData(
        calibration_name="test_calibration",
        created_at="2024-01-01T00:00:00Z",
        pitch_boundary=[
            Point2D(x=100.0, y=100.0),
            Point2D(x=1180.0, y=100.0),
            Point2D(x=1180.0, y=620.0),
            Point2D(x=100.0, y=620.0)
        ],
        crease_lines={
            "bowling": [Point2D(x=640.0, y=-10.0), Point2D(x=640.0, y=-10.0)],
            "batting": [Point2D(x=640.0, y=0.0), Point2D(x=640.0, y=0.0)]
        },
        wide_guidelines={"left": -1.0, "right": 1.0},
        stump_positions={
            "bowling": Point2D(x=640.0, y=-10.0),
            "batting": Point2D(x=640.0, y=0.0)
        },
        camera_calibrations={}
    )


# ============================================================================
# Property 23: Confidence Score Bounds
# ============================================================================

@given(
    trajectory=trajectory_strategy(min_length=5, max_length=20),
    num_detections=st.integers(min_value=1, max_value=10)
)
def test_property_23_confidence_score_bounds(trajectory, num_detections):
    """
    Property 23: Confidence Score Bounds
    
    For any decision generated by the Decision Engine, the confidence score
    SHALL be in the range [0, 100] percent (or [0.0, 1.0] as a fraction).
    
    Validates: Requirements 11.1
    """
    engine = DecisionEngine()
    calibration = CalibrationData(
        calibration_name="test_calibration",
        created_at="2024-01-01T00:00:00Z",
        pitch_boundary=[
            Point2D(x=100.0, y=100.0),
            Point2D(x=1180.0, y=100.0),
            Point2D(x=1180.0, y=620.0),
            Point2D(x=100.0, y=620.0)
        ],
        crease_lines={
            "bowling": [Point2D(x=640.0, y=-10.0), Point2D(x=640.0, y=-10.0)],
            "batting": [Point2D(x=640.0, y=0.0), Point2D(x=640.0, y=0.0)]
        },
        wide_guidelines={"left": -1.0, "right": 1.0},
        stump_positions={
            "bowling": Point2D(x=640.0, y=-10.0),
            "batting": Point2D(x=640.0, y=0.0)
        },
        camera_calibrations={}
    )
    
    # Generate random detections
    detections = []
    for _ in range(num_detections):
        confidence = np.random.uniform(0.0, 1.0)
        class_id = np.random.randint(0, 8)
        detections.append(Detection(
            class_id=class_id,
            class_name=f"class_{class_id}",
            bounding_box=BoundingBox(
                x=np.random.uniform(0.0, 1280.0),
                y=np.random.uniform(0.0, 720.0),
                width=np.random.uniform(10.0, 200.0),
                height=np.random.uniform(10.0, 200.0)
            ),
            confidence=confidence
        ))
    
    # Classify delivery
    decision = engine.classify_delivery(trajectory, detections, calibration)
    
    # Property: Confidence SHALL be in range [0.0, 1.0]
    assert 0.0 <= decision.confidence <= 1.0, (
        f"Confidence score out of bounds: {decision.confidence}. "
        f"Expected range [0.0, 1.0]"
    )


# ============================================================================
# Property 24: Low Confidence Flagging
# ============================================================================

@settings(suppress_health_check=[HealthCheck.too_slow])
@given(
    trajectory=trajectory_strategy(min_length=5, max_length=20),
    low_confidence=st.floats(min_value=0.0, max_value=0.79)
)
def test_property_24_low_confidence_flagging(trajectory, low_confidence):
    """
    Property 24: Low Confidence Flagging
    
    For any decision with confidence score below 80%, the Decision Engine
    SHALL flag the decision for manual review and log it for post-match analysis.
    
    Validates: Requirements 11.2, 11.4
    """
    engine = DecisionEngine()
    calibration = CalibrationData(
        calibration_name="test_calibration",
        created_at="2024-01-01T00:00:00Z",
        pitch_boundary=[
            Point2D(x=100.0, y=100.0),
            Point2D(x=1180.0, y=100.0),
            Point2D(x=1180.0, y=620.0),
            Point2D(x=100.0, y=620.0)
        ],
        crease_lines={
            "bowling": [Point2D(x=640.0, y=-10.0), Point2D(x=640.0, y=-10.0)],
            "batting": [Point2D(x=640.0, y=0.0), Point2D(x=640.0, y=0.0)]
        },
        wide_guidelines={"left": -1.0, "right": 1.0},
        stump_positions={
            "bowling": Point2D(x=640.0, y=-10.0),
            "batting": Point2D(x=640.0, y=0.0)
        },
        camera_calibrations={}
    )
    
    # Create detections with low confidence
    detections = [
        Detection(
            class_id=0,
            class_name="ball",
            bounding_box=BoundingBox(x=640.0, y=360.0, width=20.0, height=20.0),
            confidence=low_confidence
        )
    ]
    
    # Classify delivery
    decision = engine.classify_delivery(trajectory, detections, calibration)
    
    # Property: If confidence < 80%, requires_review SHALL be True
    if decision.confidence < 0.80:
        assert decision.requires_review is True, (
            f"Decision with confidence {decision.confidence:.2f} (<80%) "
            f"should be flagged for review, but requires_review={decision.requires_review}"
        )


# ============================================================================
# Additional Edge Case Tests
# ============================================================================

def test_decision_engine_initialization():
    """Test DecisionEngine initialization."""
    engine = DecisionEngine()
    
    assert engine.wide_detector is not None
    assert engine.no_ball_detector is not None
    assert engine.bowled_detector is not None
    assert engine.caught_detector is not None
    assert engine.lbw_detector is not None
    assert engine.legal_delivery_counter is not None


def test_decision_engine_with_config():
    """Test DecisionEngine with custom configuration."""
    config = DecisionEngineConfig(
        enable_wide_detection=False,
        enable_no_ball_detection=True,
        min_confidence_threshold=0.75,
        review_threshold=0.85
    )
    
    engine = DecisionEngine(config=config)
    
    assert engine.config.enable_wide_detection is False
    assert engine.config.enable_no_ball_detection is True
    assert engine.config.min_confidence_threshold == 0.75
    assert engine.config.review_threshold == 0.85


def test_decision_engine_config_validation():
    """Test DecisionEngineConfig validation."""
    # Valid config
    config = DecisionEngineConfig(
        min_confidence_threshold=0.70,
        review_threshold=0.80
    )
    assert config.min_confidence_threshold == 0.70
    
    # Invalid min_confidence_threshold (out of range)
    with pytest.raises(ValueError, match="min_confidence_threshold must be in range"):
        DecisionEngineConfig(min_confidence_threshold=1.5)
    
    # Invalid review_threshold (out of range)
    with pytest.raises(ValueError, match="review_threshold must be in range"):
        DecisionEngineConfig(review_threshold=-0.1)


def test_get_match_state():
    """Test get_match_state method."""
    engine = DecisionEngine()
    match_state = engine.get_match_state()
    
    assert match_state.over_number == 0
    assert match_state.ball_number == 0
    assert match_state.legal_deliveries == 0


def test_reset_match_state():
    """Test reset_match_state method."""
    engine = DecisionEngine()
    
    # Process some deliveries
    calibration = CalibrationData(
        calibration_name="test_calibration",
        created_at="2024-01-01T00:00:00Z",
        pitch_boundary=[
            Point2D(x=100.0, y=100.0),
            Point2D(x=1180.0, y=100.0),
            Point2D(x=1180.0, y=620.0),
            Point2D(x=100.0, y=620.0)
        ],
        crease_lines={
            "bowling": [Point2D(x=640.0, y=-10.0), Point2D(x=640.0, y=-10.0)],
            "batting": [Point2D(x=640.0, y=0.0), Point2D(x=640.0, y=0.0)]
        },
        wide_guidelines={"left": -1.0, "right": 1.0},
        stump_positions={
            "bowling": Point2D(x=640.0, y=-10.0),
            "batting": Point2D(x=640.0, y=0.0)
        },
        camera_calibrations={}
    )
    
    trajectory = Trajectory(
        positions=[Position3D(x=0.0, y=1.0, z=-10.0)],
        timestamps=[1.0],
        velocities=[Vector3D(vx=0.0, vy=0.0, vz=20.0)],
        start_position=Position3D(x=0.0, y=1.0, z=-10.0)
    )
    
    detections = [
        Detection(
            class_id=0,
            class_name="ball",
            bounding_box=BoundingBox(x=640.0, y=360.0, width=20.0, height=20.0),
            confidence=0.95
        )
    ]
    
    engine.classify_delivery(trajectory, detections, calibration)
    
    # Reset
    engine.reset_match_state(starting_over=5)
    
    match_state = engine.get_match_state()
    assert match_state.over_number == 5
    assert match_state.ball_number == 0
    assert match_state.legal_deliveries == 0
    assert len(engine.get_last_decisions()) == 0


def test_update_calibration():
    """Test update_calibration method."""
    engine = DecisionEngine()
    
    new_calibration = CalibrationData(
        calibration_name="test_calibration",
        created_at="2024-01-01T00:00:00Z",
        pitch_boundary=[
            Point2D(x=50.0, y=50.0),
            Point2D(x=1230.0, y=50.0),
            Point2D(x=1230.0, y=670.0),
            Point2D(x=50.0, y=670.0)
        ],
        crease_lines={
            "bowling": [Point2D(x=640.0, y=-12.0), Point2D(x=640.0, y=-12.0)],
            "batting": [Point2D(x=640.0, y=2.0), Point2D(x=640.0, y=2.0)]
        },
        wide_guidelines={"left": -1.2, "right": 1.2},
        stump_positions={
            "bowling": Point2D(x=640.0, y=-12.0),
            "batting": Point2D(x=640.0, y=2.0)
        },
        camera_calibrations={}
    )
    
    engine.update_calibration(new_calibration)
    
    assert engine.calibration == new_calibration
    assert engine.wide_detector.calibration == new_calibration
    assert engine.no_ball_detector.calibration == new_calibration


def test_get_last_decisions():
    """Test get_last_decisions method."""
    engine = DecisionEngine()
    calibration = CalibrationData(
        calibration_name="test_calibration",
        created_at="2024-01-01T00:00:00Z",
        pitch_boundary=[
            Point2D(x=100.0, y=100.0),
            Point2D(x=1180.0, y=100.0),
            Point2D(x=1180.0, y=620.0),
            Point2D(x=100.0, y=620.0)
        ],
        crease_lines={
            "bowling": [Point2D(x=640.0, y=-10.0), Point2D(x=640.0, y=-10.0)],
            "batting": [Point2D(x=640.0, y=0.0), Point2D(x=640.0, y=0.0)]
        },
        wide_guidelines={"left": -1.0, "right": 1.0},
        stump_positions={
            "bowling": Point2D(x=640.0, y=-10.0),
            "batting": Point2D(x=640.0, y=0.0)
        },
        camera_calibrations={}
    )
    
    # Make several decisions using process_frame
    for i in range(5):
        trajectory = Trajectory(
            positions=[Position3D(x=0.0, y=1.0, z=-10.0)],
            timestamps=[float(i)],
            velocities=[Vector3D(vx=0.0, vy=0.0, vz=20.0)],
            start_position=Position3D(x=0.0, y=1.0, z=-10.0)
        )
        
        detections = [
            Detection(
                class_id=0,
                class_name="ball",
                bounding_box=BoundingBox(x=640.0, y=360.0, width=20.0, height=20.0),
                confidence=0.95
            )
        ]
        
        # Create frame and detection result
        frame = Frame(
            camera_id="cam1",
            frame_number=i,
            timestamp=float(i),
            image=np.zeros((720, 1280, 3), dtype=np.uint8)
        )
        
        detection_result = DetectionResult(
            frame=frame,
            detections=detections,
            processing_time_ms=10.0
        )
        
        track_state = TrackState(
            track_id="track_1",
            position=Position3D(x=0.0, y=1.0, z=0.0),
            velocity=Vector3D(vx=0.0, vy=0.0, vz=20.0),
            acceleration=Vector3D(vx=0.0, vy=0.0, vz=0.0),
            covariance=np.eye(9),
            last_seen=float(i),
            occlusion_duration=0,
            confidence=0.95
        )
        
        engine.process_frame(detection_result, track_state, trajectory, calibration)
    
    # Get last 3 decisions
    last_decisions = engine.get_last_decisions(count=3)
    assert len(last_decisions) == 3
    
    # Get all decisions
    all_decisions = engine.get_last_decisions(count=10)
    assert len(all_decisions) == 5
