"""
Property-based tests for DecisionOutput.

These tests validate the correctness properties related to decision output
completeness and priority ordering.
"""

import pytest
from hypothesis import given, strategies as st, assume, settings, HealthCheck
import numpy as np
import time

from umpirai.output.decision_output import DecisionOutput, OutputConfig, OutputFormat, DecisionPriority
from umpirai.models.data_models import (
    Decision,
    EventType,
    Trajectory,
    Position3D,
    Vector3D,
    Detection,
    BoundingBox,
    VideoReference,
)


# ============================================================================
# Hypothesis Strategies
# ============================================================================

@st.composite
def position_3d_strategy(draw):
    """Generate random 3D positions."""
    return Position3D(
        x=draw(st.floats(min_value=-10.0, max_value=10.0)),
        y=draw(st.floats(min_value=0.0, max_value=5.0)),
        z=draw(st.floats(min_value=-20.0, max_value=20.0))
    )


@st.composite
def vector_3d_strategy(draw):
    """Generate random 3D vectors."""
    return Vector3D(
        vx=draw(st.floats(min_value=-30.0, max_value=30.0)),
        vy=draw(st.floats(min_value=-30.0, max_value=30.0)),
        vz=draw(st.floats(min_value=-30.0, max_value=30.0))
    )


@st.composite
def trajectory_strategy(draw, min_length=1, max_length=30):
    """Generate random Trajectory objects."""
    length = draw(st.integers(min_value=min_length, max_value=max_length))
    
    positions = [draw(position_3d_strategy()) for _ in range(length)]
    timestamps = sorted([draw(st.floats(min_value=0.0, max_value=10.0)) for _ in range(length)])
    velocities = [draw(vector_3d_strategy()) for _ in range(length)]
    
    return Trajectory(
        positions=positions,
        timestamps=timestamps,
        velocities=velocities,
        start_position=positions[0] if positions else Position3D(x=0.0, y=1.0, z=-10.0),
        end_position=positions[-1] if positions else None,
        speed_max=draw(st.floats(min_value=0.0, max_value=50.0)),
        speed_avg=draw(st.floats(min_value=0.0, max_value=40.0))
    )


@st.composite
def detection_strategy(draw, class_id=None, confidence=None):
    """Generate random Detection objects."""
    if class_id is None:
        class_id = draw(st.integers(min_value=0, max_value=7))
    if confidence is None:
        confidence = draw(st.floats(min_value=0.0, max_value=1.0))
    
    return Detection(
        class_id=class_id,
        class_name=f"class_{class_id}",
        bounding_box=BoundingBox(
            x=draw(st.floats(min_value=0.0, max_value=1280.0)),
            y=draw(st.floats(min_value=0.0, max_value=720.0)),
            width=draw(st.floats(min_value=10.0, max_value=200.0)),
            height=draw(st.floats(min_value=10.0, max_value=200.0))
        ),
        confidence=confidence,
        position_3d=draw(st.one_of(st.none(), position_3d_strategy()))
    )


@st.composite
def decision_strategy(draw, event_type=None):
    """Generate random Decision objects."""
    if event_type is None:
        event_type = draw(st.sampled_from(list(EventType)))
    
    trajectory = draw(trajectory_strategy(min_length=2, max_length=10))
    detections = [draw(detection_strategy()) for _ in range(draw(st.integers(min_value=1, max_value=5)))]
    
    timestamp = time.time()
    
    return Decision(
        decision_id=f"decision_{draw(st.integers(min_value=1, max_value=10000))}",
        event_type=event_type,
        confidence=draw(st.floats(min_value=0.0, max_value=1.0)),
        timestamp=timestamp,
        trajectory=trajectory,
        detections=detections,
        reasoning=draw(st.text(min_size=10, max_size=100)),
        video_references=[
            VideoReference(
                camera_id="cam1",
                frame_number=draw(st.integers(min_value=0, max_value=10000)),
                timestamp=timestamp
            )
        ],
        requires_review=draw(st.booleans())
    )


# ============================================================================
# Property 21: Decision Output Completeness
# ============================================================================

@given(decision=decision_strategy())
def test_property_21_decision_output_completeness(decision):
    """
    Property 21: Decision Output Completeness
    
    For any decision generated by the Decision Engine, the Decision_Output
    SHALL include the event type, confidence level, and timestamp.
    
    **Validates: Requirements 10.2, 10.4, 11.3**
    """
    # Create output handler with text-only output (no audio/visual dependencies)
    config = OutputConfig(enable_text=True, enable_audio=False, enable_visual=False)
    output_handler = DecisionOutput(config=config)
    
    # Display decision (without frame, will print to console)
    output_handler.display_decision(decision, frame=None)
    
    # Verify that latency was measured (indicates output was generated)
    latency_stats = output_handler.get_latency_stats()
    assert latency_stats["count"] > 0, "No output was generated"
    
    # Verify latency measurement includes timestamp information
    assert latency_stats["latest_ms"] >= 0.0, "Latency measurement invalid"
    
    # Verify decision contains required fields
    assert decision.event_type is not None, "Decision missing event_type"
    assert decision.confidence is not None, "Decision missing confidence"
    assert decision.timestamp is not None, "Decision missing timestamp"
    
    # Verify event type is valid
    assert isinstance(decision.event_type, EventType), "event_type is not EventType enum"
    
    # Verify confidence is in valid range
    assert 0.0 <= decision.confidence <= 1.0, f"Confidence {decision.confidence} out of range [0.0, 1.0]"
    
    # Verify timestamp is valid
    assert decision.timestamp > 0.0, "Timestamp must be positive"
    
    # Verify formatted text includes event type
    formatted_text = output_handler._format_decision_text(decision, latency_stats["latest_ms"])
    event_name = decision.event_type.value.upper().replace("_", " ")
    assert event_name in formatted_text, f"Event type '{event_name}' not in output text: {formatted_text}"
    
    # Verify formatted text includes confidence
    confidence_pct = decision.confidence * 100
    assert f"{confidence_pct:.1f}%" in formatted_text, f"Confidence not in output text: {formatted_text}"
    
    # Verify formatted text includes latency (which is derived from timestamp)
    assert "Latency:" in formatted_text, f"Latency not in output text: {formatted_text}"


# ============================================================================
# Property 22: Decision Priority Ordering
# ============================================================================

@given(
    dismissal_event=st.sampled_from([EventType.BOWLED, EventType.CAUGHT, EventType.LBW]),
    other_event=st.sampled_from([EventType.WIDE, EventType.NO_BALL, EventType.LEGAL])
)
def test_property_22_decision_priority_ordering(dismissal_event, other_event):
    """
    Property 22: Decision Priority Ordering
    
    For any set of simultaneous match events that includes a Dismissal_Event,
    the system SHALL prioritize the Dismissal_Event output over other event types.
    
    **Validates: Requirements 10.5**
    """
    # Create output handler
    config = OutputConfig(enable_text=True, enable_audio=False, enable_visual=False)
    output_handler = DecisionOutput(config=config)
    
    # Create dismissal decision
    dismissal_decision = Decision(
        decision_id="dismissal_1",
        event_type=dismissal_event,
        confidence=0.90,
        timestamp=time.time(),
        trajectory=Trajectory(
            positions=[Position3D(x=0.0, y=1.0, z=-10.0)],
            timestamps=[1.0],
            velocities=[Vector3D(vx=0.0, vy=0.0, vz=20.0)],
            start_position=Position3D(x=0.0, y=1.0, z=-10.0)
        ),
        detections=[
            Detection(
                class_id=0,
                class_name="ball",
                bounding_box=BoundingBox(x=640.0, y=360.0, width=20.0, height=20.0),
                confidence=0.95
            )
        ],
        reasoning="Dismissal detected",
        video_references=[VideoReference(camera_id="cam1", frame_number=100, timestamp=1.0)],
        requires_review=False
    )
    
    # Create other decision
    other_decision = Decision(
        decision_id="other_1",
        event_type=other_event,
        confidence=0.85,
        timestamp=time.time(),
        trajectory=Trajectory(
            positions=[Position3D(x=0.0, y=1.0, z=-10.0)],
            timestamps=[1.0],
            velocities=[Vector3D(vx=0.0, vy=0.0, vz=20.0)],
            start_position=Position3D(x=0.0, y=1.0, z=-10.0)
        ),
        detections=[
            Detection(
                class_id=0,
                class_name="ball",
                bounding_box=BoundingBox(x=640.0, y=360.0, width=20.0, height=20.0),
                confidence=0.90
            )
        ],
        reasoning="Other event detected",
        video_references=[VideoReference(camera_id="cam1", frame_number=100, timestamp=1.0)],
        requires_review=False
    )
    
    # Get priorities
    dismissal_priority = output_handler.get_decision_priority(dismissal_decision)
    other_priority = output_handler.get_decision_priority(other_decision)
    
    # Property: Dismissal events SHALL have higher priority than other events
    assert dismissal_priority == DecisionPriority.HIGH, (
        f"Dismissal event {dismissal_event} should have HIGH priority, got {dismissal_priority}"
    )
    
    assert other_priority.value < dismissal_priority.value, (
        f"Dismissal priority ({dismissal_priority.value}) should be higher than "
        f"other event priority ({other_priority.value})"
    )
    
    # Verify priority values
    assert dismissal_priority.value == 3, "HIGH priority should be 3"
    assert other_priority.value <= 2, "Non-dismissal priority should be <= 2"


# ============================================================================
# Additional Property Tests
# ============================================================================

@settings(suppress_health_check=[HealthCheck.too_slow])
@given(
    decisions=st.lists(decision_strategy(), min_size=2, max_size=5)
)
def test_property_dismissal_always_highest_priority(decisions):
    """
    Test that dismissal events always have the highest priority among any set of decisions.
    """
    output_handler = DecisionOutput()
    
    # Get priorities for all decisions
    priorities = [output_handler.get_decision_priority(d) for d in decisions]
    
    # Find dismissal decisions
    dismissal_indices = [
        i for i, d in enumerate(decisions)
        if d.event_type in (EventType.BOWLED, EventType.CAUGHT, EventType.LBW)
    ]
    
    # If there are dismissal decisions, they should all have HIGH priority
    for idx in dismissal_indices:
        assert priorities[idx] == DecisionPriority.HIGH, (
            f"Dismissal event {decisions[idx].event_type} should have HIGH priority"
        )
    
    # If there are dismissal decisions, no other decision should have higher priority
    if dismissal_indices:
        dismissal_priority_value = DecisionPriority.HIGH.value
        for i, priority in enumerate(priorities):
            if i not in dismissal_indices:
                assert priority.value <= dismissal_priority_value, (
                    f"Non-dismissal event {decisions[i].event_type} has priority {priority.value} "
                    f"which is not less than or equal to dismissal priority {dismissal_priority_value}"
                )


@given(decision=decision_strategy())
def test_property_latency_measurement_non_negative(decision):
    """
    Test that latency measurements are always non-negative.
    """
    config = OutputConfig(enable_text=True, enable_audio=False, enable_visual=False)
    output_handler = DecisionOutput(config=config)
    
    # Display decision
    output_handler.display_decision(decision, frame=None)
    
    # Get latency stats
    stats = output_handler.get_latency_stats()
    
    # All latency measurements should be non-negative
    assert stats["min_ms"] >= 0.0, "Minimum latency should be non-negative"
    assert stats["max_ms"] >= 0.0, "Maximum latency should be non-negative"
    assert stats["avg_ms"] >= 0.0, "Average latency should be non-negative"
    assert stats["latest_ms"] >= 0.0, "Latest latency should be non-negative"


@given(
    event_type=st.sampled_from(list(EventType))
)
def test_property_all_event_types_have_priority(event_type):
    """
    Test that all event types have a defined priority.
    """
    output_handler = DecisionOutput()
    
    # Create a decision with the event type
    decision = Decision(
        decision_id="test_1",
        event_type=event_type,
        confidence=0.90,
        timestamp=time.time(),
        trajectory=Trajectory(
            positions=[Position3D(x=0.0, y=1.0, z=-10.0)],
            timestamps=[1.0],
            velocities=[Vector3D(vx=0.0, vy=0.0, vz=20.0)],
            start_position=Position3D(x=0.0, y=1.0, z=-10.0)
        ),
        detections=[],
        reasoning="Test",
        video_references=[],
        requires_review=False
    )
    
    # Get priority
    priority = output_handler.get_decision_priority(decision)
    
    # Priority should be a valid DecisionPriority enum
    assert isinstance(priority, DecisionPriority), (
        f"Priority for {event_type} should be DecisionPriority enum, got {type(priority)}"
    )
    
    # Priority value should be valid (1, 2, or 3)
    assert priority.value in (1, 2, 3), (
        f"Priority value for {event_type} should be 1, 2, or 3, got {priority.value}"
    )


@given(
    output_format=st.sampled_from(list(OutputFormat))
)
def test_property_output_format_configuration(output_format):
    """
    Test that output format can be configured and retrieved correctly.
    """
    output_handler = DecisionOutput()
    
    # Set output format
    output_handler.set_output_format(output_format)
    
    # Get output format
    retrieved_format = output_handler.get_output_format()
    
    # For specific formats, verify the configuration
    if output_format == OutputFormat.TEXT:
        assert output_handler.config.enable_text is True
        assert output_handler.config.enable_audio is False
        assert output_handler.config.enable_visual is False
        assert retrieved_format == OutputFormat.TEXT
    elif output_format == OutputFormat.AUDIO:
        assert output_handler.config.enable_text is False
        assert output_handler.config.enable_audio is True
        assert output_handler.config.enable_visual is False
        assert retrieved_format == OutputFormat.AUDIO
    elif output_format == OutputFormat.VISUAL:
        assert output_handler.config.enable_text is False
        assert output_handler.config.enable_audio is False
        assert output_handler.config.enable_visual is True
        assert retrieved_format == OutputFormat.VISUAL
    elif output_format == OutputFormat.ALL:
        assert output_handler.config.enable_text is True
        assert output_handler.config.enable_audio is True
        assert output_handler.config.enable_visual is True
        assert retrieved_format == OutputFormat.ALL
